/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: fichier.proto */

#ifndef PROTOBUF_C_fichier_2eproto__INCLUDED
#define PROTOBUF_C_fichier_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _ArretUrgence ArretUrgence;
typedef struct _BatteryLevel BatteryLevel;


/* --- enums --- */


/* --- messages --- */

struct  _ArretUrgence
{
  ProtobufCMessage base;
  /*
   * Niveau de la batterie
   */
  uint32_t level;
};
#define ARRET_URGENCE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&arret_urgence__descriptor) \
    , 0 }


struct  _BatteryLevel
{
  ProtobufCMessage base;
  /*
   * Niveau de la batterie
   */
  uint32_t level;
};
#define BATTERY_LEVEL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&battery_level__descriptor) \
    , 0 }


/* ArretUrgence methods */
void   arret_urgence__init
                     (ArretUrgence         *message);
size_t arret_urgence__get_packed_size
                     (const ArretUrgence   *message);
size_t arret_urgence__pack
                     (const ArretUrgence   *message,
                      uint8_t             *out);
size_t arret_urgence__pack_to_buffer
                     (const ArretUrgence   *message,
                      ProtobufCBuffer     *buffer);
ArretUrgence *
       arret_urgence__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   arret_urgence__free_unpacked
                     (ArretUrgence *message,
                      ProtobufCAllocator *allocator);
/* BatteryLevel methods */
void   battery_level__init
                     (BatteryLevel         *message);
size_t battery_level__get_packed_size
                     (const BatteryLevel   *message);
size_t battery_level__pack
                     (const BatteryLevel   *message,
                      uint8_t             *out);
size_t battery_level__pack_to_buffer
                     (const BatteryLevel   *message,
                      ProtobufCBuffer     *buffer);
BatteryLevel *
       battery_level__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   battery_level__free_unpacked
                     (BatteryLevel *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ArretUrgence_Closure)
                 (const ArretUrgence *message,
                  void *closure_data);
typedef void (*BatteryLevel_Closure)
                 (const BatteryLevel *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor arret_urgence__descriptor;
extern const ProtobufCMessageDescriptor battery_level__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_fichier_2eproto__INCLUDED */
