exploration_protobuf_c: c/src/com/com.h File Reference
com.h File Reference
Interface pour la gestion de la communication entre serveur et client.
#include "../protocole/protocole.h"
Macros
#define TRACE(...)
Macro pour la sortie de débogage conditionnelle.
Functions
void com_init ()
Initialise la file de messages pour l'écriture.
void com_free ()
Libère les ressources utilisées par le système de communication.
void com_start ()
Démarre le système de communication.
void com_stop ()
Arrête le système de communication.
void com_send_message (message_t *message)
Envoie un message à travers la file de messages.
Detailed Description
Interface pour la gestion de la communication entre serveur et client.
Ce fichier définit les structures et prototypes nécessaires pour la gestion de la communication réseau entre un serveur et un client.
Definition in file com.h.
Macro Definition Documentation
TRACE
#define TRACE (...)
Macro pour la sortie de débogage conditionnelle.
Cette macro permet l'affichage de messages de débogage si le mode DEBUG est activé. Elle ne fait rien en mode de production (lorsque DEBUG n'est pas défini).
Definition at line 23 of file com.h.
Function Documentation
com_free()
void com_free ()
Libère les ressources utilisées par le système de communication.
Ferme la file de messages et la supprime.
Definition at line 104 of file com.c.
                {
     // Fermeture de la file de messages
     if (mq_close(mq_write) == -1) {
         perror("COM | thread_write_fct : Erreur fermeture mq_write");
         exit(EXIT_FAILURE);
     }
     TRACE("COM | com_free : Fermeture mq_write réussie\n");
     // Suppression de la file de messages
     if (mq_unlink(MQ_WRITE_NAME) == -1) {
         perror("COM | thread_write_fct : Erreur suppression mq_write");
         exit(EXIT_FAILURE);
     }
     TRACE("COM | com_free : Suppression mq_write réussie\n");
 }
References TRACE.
com_init()
void com_init ()
Initialise la file de messages pour l'écriture.
Crée et configure la file de messages.
Definition at line 86 of file com.c.
                 {
     // Configuration et ouverture de la file de messages
     struct mq_attr attr;
     attr.mq_flags = 0;
     attr.mq_maxmsg = 10;
     attr.mq_msgsize = sizeof(message_t);
     mq_write = mq_open(MQ_WRITE_NAME, O_CREAT | O_RDWR, 0644, &attr);
     if (mq_write == (mqd_t ) -1)
     {
         perror("COM | com_init : Erreur création mq\n");
         mq_unlink( MQ_WRITE_NAME );
         mq_write = mq_open( MQ_WRITE_NAME , O_RDWR  |O_CREAT, 0644, &attr);
     }
     TRACE("COM | com_init : mq_write créée avec succès\n");
     com_start();
 }
References com_start(), and TRACE.
com_send_message()
void com_send_message (message_t * message)
Envoie un message à travers la file de messages.
Parameters
message Le message à envoyer.
Definition at line 78 of file com.c.
{
     if (mq_send(mq_write, (const char *) message, sizeof(message_t), 0) == -1) {
         perror("COM | com_send_message : mq_send");
         exit(EXIT_FAILURE);
     }
 }
Referenced by com_stop().
com_start()
void com_start ()
Démarre le système de communication.
Initialise la connexion et lance les threads de lecture et d'écriture.
Definition at line 28 of file com.c.
                 {
     // Ouverture du serveur sur le port SERVEUR_PORT
     connexion_init(SERVER_PORT);
     // Attente d'une connexion client
     printf("COM | com_init : En attente de connexion\n");
     socket_client = connexion_accept();
     running = 1;
     // Lancement du thread d'écriture
     if (pthread_create(&thread_write, NULL, thread_write_fct, NULL) != 0) {
         perror("COM | com_init : erreur pthread_create thread_write");
         exit(-1);
     }
     TRACE("COM | com_start : thread_write lancé\n");
     // Lancement du thread de lecture
     if (pthread_create(&thread_read, NULL, thread_read_fct, NULL) != 0) {
         perror("COM | com_init : erreur pthread_create thread_read");
         exit(-1);
     }
     TRACE("COM | com_start : thread_read lancé\n");
 }
References connexion_accept(), connexion_init(), SERVER_PORT, and TRACE.
Referenced by com_init().
com_stop()
void com_stop ()
Arrête le système de communication.
Envoie un message d'arrêt, ferme la connexion et les threads.
Definition at line 53 of file com.c.
                {
     running = 0;
     // Envoi d'un message d'arrêt
     message_t msg_stop;
     msg_stop.dlc = 0x02;
     msg_stop.id = 0XAA;
     msg_stop.payload[0] = 100;
     com_send_message(&msg_stop);
     // Fermeture de la connexion
     connexion_close();
     // Attente de la fin des threads
     if (pthread_join(thread_write, NULL) != 0) {
         perror("COM | com_stop : erreur pthread_join thread_write");
     }
     TRACE("COM | com_stop : thread_write stopped\n");
     if (pthread_join(thread_read, NULL) != 0) {
         perror("COM | com_stop : erreur pthread_join thread_read");
     }
     TRACE("COM | com_stop : thread_read stopped\n");
 }
References com_send_message(), connexion_close(), message_t::dlc, message_t::id, message_t::payload, and TRACE.